name: Build Overflow for Windows
on: [push]

jobs:
  create:
    runs-on: windows-latest
    steps:
      - name: Get repo files
        uses: actions/checkout@v3
        
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build
        run: msbuild Overflow.sln
