name: Build Overflow for Windows
on: [push]

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo files
        uses: actions/checkout@v3
      
      - name: Build
        run: mono-msbuild Overflow.sln
